name: Linter

# Trigger on push
on: push

jobs:
  linter:
    name: Run Linter

    # Runs on latest ubuntu version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - # Set up meteor
        name: Use Latest Meteor
        run: curl https://install.meteor.com/ | sh
      - # Install dependencies
        name: Install dependencies
        run: meteor npm ci
      - # Lint typescript-files and annotate issues
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "*.ts"
