name: Linter

# Trigger on push
on: [push]

jobs:
  runner:
    name: Runner

    # Runs on latest ubuntu version
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - # Set up meteor
        name: Use Latest Meteor
        run: curl https://install.meteor.com/ | sh
      - # Install dependencies
        name: Install dependencies
        run: meteor npm ci
      - # Lint typescript-files and annotate issues for imports
        name: TSLint Checks for Imports
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "imports/**/*.ts"
      - # Lint typescript-files and annotate issues for server
        name: TSLint Checks for Server
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "server/**/*.ts"
      - # Lint typescript-files and annotate issues for client
        name: TSLint Checks for Client
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "client/**/*.ts"
