name: Linter

# Trigger on push
on: push

jobs:
  linter:
    name: Run Linter
    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: Install dependencies
        working-directory: .
        run: npm install
      - name: Lint
        working-directory: .
        run: npm run lint
