name: Linter

# Trigger on push
on: push

jobs:
  linter:
    name: Run Linter

    # Runs on latest ubuntu version
    runs-on: ubuntu-latest
    steps:
      - # Set up meteor
        name: Use Latest Meteor
        run: curl https://install.meteor.com/ | sh
      - # Install dependencies
        name: Install dependencies
        run: meteor npm install
      - # Run our linting script without fixing issues
        name: Lint
        run: meteor npm run lint
