name: Mocha

# Trigger on push
on: [push]

jobs:
  runner:
    name: Runner

    # Runs on ubuntu version 18.04
    runs-on: ubuntu-18.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - # Set up meteor
        name: Install Latest Meteor
        run: curl https://install.meteor.com/ | sh
      - # Install dependencies
        name: Install dependencies
        run: meteor npm ci
      - # Setup Chromedriver
        name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@v1.0.1
      - # Run our testing script
        name: Mocha
        run: meteor npm run test:ci
